### ISSUE TITLE
Question about how to calculate Attribution Accuracy

### ISSUE THREAD

**Issue by xinxinzi8** [kylemin/WOUAF#1]
Hello, author! I'd like to know how to calculate attribution accuracy in your paper using this code. Is the file `bitwiseacc.py`  used to calculate it?
I am looking forward to your reply. Thank you very much!

**Comment by kylemin** [comment]
Thank you for your interest in our work. Yes, `bitwiseacc.py` is used to compute the accuracy of the attribution. We also used `attackacc.py` for Figure 5.

**Comment by xinxinzi8** [comment]
Thank you for your reply!
