### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by chbw818** [kylemin/WOUAF#2]
Hi！Great work！
I have a small question about the distribution process,because i'm new to this and i may misunderstood the code.
Does the model owner need to provide both the VAE decoder and intermediate fingerprint to the user simultaneously?

**Comment by kylemin** [comment]
Thank you for your interest in our work.
No, the model owners (distributors) are not supposed to distribute the fingerprint. They keep the user-specific fingerprints in their database. I hope this helps!

**Comment by chbw818** [comment]
Thanks！I read the paper and the code again and I unerstood.
